<?php

/* This file was autogenerated by spec/parser.php - Do not modify */

namespace PhpAmqpLib\Helper\Protocol;

class MethodMap080
{
    /**
     * @var array
     */
    protected $methodMap = array(
        '10,10' => 'connectionStart',
        '10,11' => 'connectionStartOk',
        '10,20' => 'connectionSecure',
        '10,21' => 'connectionSecureOk',
        '10,30' => 'connectionTune',
        '10,31' => 'connectionTuneOk',
        '10,40' => 'connectionOpen',
        '10,41' => 'connectionOpenOk',
        '10,50' => 'connectionRedirect',
        '10,60' => 'connectionClose',
        '10,61' => 'connectionCloseOk',
        '20,10' => 'channelOpen',
        '20,11' => 'channelOpenOk',
        '20,20' => 'channelFlow',
        '20,21' => 'channelFlowOk',
        '20,30' => 'channelAlert',
        '20,40' => 'channelClose',
        '20,41' => 'channelCloseOk',
        '30,10' => 'accessRequest',
        '30,11' => 'accessRequestOk',
        '40,10' => 'exchangeDeclare',
        '40,11' => 'exchangeDeclareOk',
        '40,20' => 'exchangeDelete',
        '40,21' => 'exchangeDeleteOk',
        '50,10' => 'queueDeclare',
        '50,11' => 'queueDeclareOk',
        '50,20' => 'queueBind',
        '50,21' => 'queueBindOk',
        '50,30' => 'queuePurge',
        '50,31' => 'queuePurgeOk',
        '50,40' => 'queueDelete',
        '50,41' => 'queueDeleteOk',
        '50,50' => 'queueUnbind',
        '50,51' => 'queueUnbindOk',
        '60,10' => 'basicQos',
        '60,11' => 'basicQosOk',
        '60,20' => 'basicConsume',
        '60,21' => 'basicConsumeOk',
        '60,30' => 'basicCancel',
        '60,31' => 'basicCancelOk',
        '60,40' => 'basicPublish',
        '60,50' => 'basicReturn',
        '60,60' => 'basicDeliver',
        '60,70' => 'basicGet',
        '60,71' => 'basicGetOk',
        '60,72' => 'basicGetEmpty',
        '60,80' => 'basicAck',
        '60,90' => 'basicReject',
        '60,100' => 'basicRecoverAsync',
        '60,110' => 'basicRecover',
        '60,111' => 'basicRecoverOk',
        '70,10' => 'fileQos',
        '70,11' => 'fileQosOk',
        '70,20' => 'fileConsume',
        '70,21' => 'fileConsumeOk',
        '70,30' => 'fileCancel',
        '70,31' => 'fileCancelOk',
        '70,40' => 'fileOpen',
        '70,41' => 'fileOpenOk',
        '70,50' => 'fileStage',
        '70,60' => 'filePublish',
        '70,70' => 'fileReturn',
        '70,80' => 'fileDeliver',
        '70,90' => 'fileAck',
        '70,100' => 'fileReject',
        '80,10' => 'stream_qos',
        '80,11' => 'stream_qos_ok',
        '80,20' => 'stream_consume',
        '80,21' => 'stream_consume_ok',
        '80,30' => 'stream_cancel',
        '80,31' => 'stream_cancel_ok',
        '80,40' => 'stream_publish',
        '80,50' => 'stream_return',
        '80,60' => 'streamDeliver',
        '90,10' => 'txSelect',
        '90,11' => 'txSelectOk',
        '90,20' => 'txCommit',
        '90,21' => 'txCommitOk',
        '90,30' => 'txRollback',
        '90,31' => 'txRollbackOk',
        '100,10' => 'dtxSelect',
        '100,11' => 'dtxSelectOk',
        '100,20' => 'dtxStart',
        '100,21' => 'dtxStartOk',
        '110,10' => 'tunnelRequest',
        '120,10' => 'testInteger',
        '120,11' => 'testIntegerOk',
        '120,20' => 'testString',
        '120,21' => 'testStringOk',
        '120,30' => 'testTable',
        '120,31' => 'testTableOk',
        '120,40' => 'testContent',
        '120,41' => 'testContentOk',
    );

    /**
     * @var string $methodSig
     * @return string
     */
    public function getMethod($methodSig)
    {
        return $this->methodMap[$methodSig];
    }

    /**
     * @var string $methodSig
     * @return bool
     */
    public function validMethod($methodSig)
    {
        return array_key_exists($methodSig, $this->methodMap);
    }
}
