<?php

/* This file was autogenerated by spec/parser.php - Do not modify */

namespace PhpAmqpLib\Helper\Protocol;

class MethodMap091
{
    /**
     * @var array
     */
    protected $methodMap = array(
        '10,10' => 'connectionStart',
        '10,11' => 'connectionStartOk',
        '10,20' => 'connectionSecure',
        '10,21' => 'connectionSecureOk',
        '10,30' => 'connectionTune',
        '10,31' => 'connectionTuneOk',
        '10,40' => 'connectionOpen',
        '10,41' => 'connectionOpenOk',
        '10,50' => 'connectionClose',
        '10,51' => 'connectionCloseOk',
        '10,60' => 'connectionBlocked',
        '10,61' => 'connectionUnblocked',
        '20,10' => 'channelOpen',
        '20,11' => 'channelOpenOk',
        '20,20' => 'channelFlow',
        '20,21' => 'channelFlowOk',
        '20,40' => 'channelClose',
        '20,41' => 'channelCloseOk',
        '30,10' => 'accessRequest',
        '30,11' => 'accessRequestOk',
        '40,10' => 'exchangeDeclare',
        '40,11' => 'exchangeDeclareOk',
        '40,20' => 'exchangeDelete',
        '40,21' => 'exchangeDeleteOk',
        '40,30' => 'exchangeBind',
        '40,31' => 'exchangeBindOk',
        '40,40' => 'exchangeUnbind',
        '40,51' => 'exchangeUnbindOk',
        '50,10' => 'queueDeclare',
        '50,11' => 'queueDeclareOk',
        '50,20' => 'queueBind',
        '50,21' => 'queueBindOk',
        '50,30' => 'queuePurge',
        '50,31' => 'queuePurgeOk',
        '50,40' => 'queueDelete',
        '50,41' => 'queueDeleteOk',
        '50,50' => 'queueUnbind',
        '50,51' => 'queueUnbindOk',
        '60,10' => 'basicQos',
        '60,11' => 'basicQosOk',
        '60,20' => 'basicConsume',
        '60,21' => 'basicConsumeOk',
        '60,30' => 'basicCancelFromServer',
        '60,31' => 'basicCancelOk',
        '60,40' => 'basicPublish',
        '60,50' => 'basicReturn',
        '60,60' => 'basicDeliver',
        '60,70' => 'basicGet',
        '60,71' => 'basicGetOk',
        '60,72' => 'basicGetEmpty',
        '60,80' => 'basicAckFromServer',
        '60,90' => 'basicReject',
        '60,100' => 'basicRecoverAsync',
        '60,110' => 'basicRecover',
        '60,111' => 'basicRecoverOk',
        '60,120' => 'basicNackFromServer',
        '90,10' => 'txSelect',
        '90,11' => 'txSelectOk',
        '90,20' => 'txCommit',
        '90,21' => 'txCommitOk',
        '90,30' => 'txRollback',
        '90,31' => 'txRollbackOk',
        '85,10' => 'confirmSelect',
        '85,11' => 'confirmSelectOk',
    );

    /**
     * @var string $methodSig
     * @return string
     */
    public function getMethod($methodSig)
    {
        return $this->methodMap[$methodSig];
    }

    /**
     * @var string $methodSig
     * @return bool
     */
    public function validMethod($methodSig)
    {
        return array_key_exists($methodSig, $this->methodMap);
    }
}
